# error codes
DEFAULT_HTTP_ERROR_CODE = 500
DEFAULT_ERROR_CODE = 5000
BAD_REQUEST_CODE = 400
SUCCESS_CODE = 200
DEFAULT_HTTP_ERROR_MESSAGE = "Internal Server Error"
DEFAULT_AUDIT_ERROR_MESSAGE = "Audit Service Error"
DEFAULT_DSAR_ERROR_MESSAGE = "DSAR Request Error"
DEFAULT_RABBITMQ_ERROR_MESSAGE = "RabbitMQ Error"
CONFLICT_HTTP_ERROR_CODE = 409
NO_CONTENT_CODE = 204
NOT_FOUND = 404
FORBIDDEN_CODE = 403
ALREADY_REPORTED = 208
ENTITY_CREATED = 201

# form data messages
INVALID_FORM_MESSAGE = "Invalid form fields. Please check again the data you have entered."
